name: "Hello Actions" 
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    dafult: "World!"
  YOUR_NAME:
    description: "Who is greeting"
    required: true
    dafult: "TOAST!"
    
runs:
  using: "docker"
  image: "Dockerfile"
  
branding: 
  icon: "mic"
  color: "purple"
